### ISSUE TITLE
Support for redis backup in node CLI

### ISSUE THREAD

**Issue by diegoquintanav** [AuroralH2020/auroral-node#1]
Hello, Auroral team!

Thanks for the great work. I've noticed that the support for Redis in the backup task in the CLI is missing, in the line 

https://github.com/AuroralH2020/auroral-node/blob/210769641a1610a124190aa270cdc4b85106c144/node_cli.sh#L201

An incomplete backup means the loss of existing TDs in the node, as I've noticed when migrating a dummy node. It was dummy data so it's okay,

Thanks!

**Comment by Joralmi** [comment]
Hello Diego, the migration covers TDs and certain parts of Redis. Not all the info in Redis is persistant between restarts, but that is how it is intended.
There are also options to export to file and load TDs afterwards for doing version migration (See migration tutorial in the blog  -- https://blog.bavenir.eu/auroral/migrating-from-old-gtw --)
