### ISSUE TITLE
Method for RPCs

### ISSUE THREAD

**Issue by hrdinka** [AuroralH2020/auroral-node#2]
Hi everyone!

We would like to use the AURORAL node for more advanced services (not just data). We haven’t found a way yet to do remote procedure calls using the AURORAL middleware. In the today’s Austrian technical meeting, some colleagues suggested that this is already possible and document within this WIKI, which it is not.

In case we have missed it and this is possible we would be happy about some directions and information on how to do this. If not we would like to see this in future versions of the AURORAL middleware.

Here are a few simple examples of we would like to be able to do:

# Search activities

`POST` request to `https://…/search_activities` with JSON request body:

```
{ "date_from": "2022-10-20"
, "language": "de"
, "latitude": 47.461526
, "longitude": 13.256694
, "search_config_id": "31214887-fecd-478f-b6b3-7456000949b5",
, "search_radius_m": 100000
, "query": "some words"
}
```

Returns a list of matching activity search results:

```
[ { "activity_id": …
  , "distance_m": …
  , "title": …
  , "image": …
  …
  }
…
]
```

# Geocoding

`POST` https://…/geocode

```
{ "query": "My Street 5, 8238 My City" }
```

Returns matching clean addresses and geocoordinates.
```
[ { "address": { … }
  , "latitude": …
  , "longitude": …
  }
]
```

**Comment by rphenriques** [comment]
Hi! 

Did you take a look at https://github.com/AuroralH2020/auroral-node-red-examples and see how you can leverage on the programatic adapter and Node-Red's capabilities and extensions to do that? Also, there is a custom adapter which can be used/extended/modified in some more specific use cases: https://github.com/AuroralH2020/auroral_custom_adapter_example.

**Comment by Joralmi** [comment]
Hello, 
What you are suggesting sounds to me as the functionality we have envisioned for services (understand service as an addon connected to a Node but not a core part of the Node).
The Node supports sending query parameters and also semantic data querying, but not AI or advanced analytical features.
We can discuss in more detail during our face2face meeting what you need, and then we can decide what a service is needed or we can provide an update to the core functionality.

**Comment by hrdinka** [comment]
@rphenriques Thanks for your comment. As far as I can see the examples don’t do anything like that. The AURORAL [API](https://auroralh2020.github.io/auroral-node-agent/) does only allow for read/write calls to obejcts/items/properties.

@Joralmi So in the end we will be able to attach any kind of API and just use the Node for data transmission? How does sending query parameters currently work? I am looking forward to our meeting. However I will only attend remotely, since I am currently abroad. We can also further discuss these in a technical or 1:1 meeting.

**Comment by rphenriques** [comment]
@hrdinka if you need to fetch data from an RPC service endpoint from a consumer (through AURORAL middleware) you (through the consumer's node) send a request to consume that data to the "producer's" node which, though an adapter, translates that request to the data provider. Same goes for any other type of provider, changing the adapter or how the adapter works. Maybe I'm missing something on your envisioned workflow? Can you provide a use case/example with the actors involved?

**Comment by hrdinka** [comment]
@rphenriques We would like to send data to an AURORAL node API endpoint and get data back. This does not seem to be possible at the moment. Currently only queries to read/write (GET/PUT) a property of a  predefined object can be done. It does not seem possible to send any query data. Currently you can have an object `Vienna` and query its property `temperature`. What you cannot do is to query the same function/endpoint and send different city names to it. For example

```
POST /$node_id/rpc/get_weather_forecast
…

{ "city": "Vienna" }
```

Please also have a look at my examples above. How would you handle such requests with the current Node implementations?

**Comment by rphenriques** [comment]
Hi @hrdinka, there's always 2 nodes involved as nodes communicate between them. 

So, you have a UI that wants to show Vienna's weather that needs to be fetched from an RPC endpoint. 
In this case:

- You have the UI connected to node A. 
- The UI  sends a GET request to node A asking for the property "weather" from node B, with additional params {"city": "Vienna"}. 
- Node B receives that request and modifies it according to comply with the weather service API (this is the adapter working). 
- The weather service gets that request, processes it and sends the response back to node B, which sends it to node A, which sends it to the UI. 

(I simplified some things by not mentioning permissions, thing descriptions and other details, but it's the overall picture). 

Does it answer your scenario?

@Joralmi, did I miss anything?

**Comment by hrdinka** [comment]
Thanks for your answer. How can I make a query with additional parameters? How can I make requests with another verb than GET?

**Comment by rphenriques** [comment]
Glad to help!
You can add the additional parameters on the query string for the GET (you can try the API in the link you provided and see how the query results). 

(Using the request body in the GET method to pass parameters is getting more accepted under HTTP, but not sure if AURORAL node does anything with it, so not sure if you can use it. @Joralmi ?)

As for the verbs, there's GET for reading properties and PUT for updating properties. (I understand you're usage of POST to actually get something because of the body part, but it's highly debated within REST).

**Comment by hrdinka** [comment]
Ok. So query parameters and request bodies (for the PUT request) get transferred transparently to the URL given in the href of the thing description. That was the information we were looking for :smile: I will try this out and get back to you if we have any problems. Thanks to both of your, this helps us a lot!

PUT/POST isn‘t a big problem. We will use a proxy in between that transforms all requests.
